In [3]:
import zipfile
import pandas as pd

Not really relevent anymore, just had to split the training file to make it small enough to upload to github

Then I had unzip some stuff, then re-zip

In [2]:
# # Open the zip file
# zip_path = "optiver-trading-at-the-close.zip"
# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     # List all file names in the zip archive
#     file_list = zip_ref.namelist()
    
#     # Iterate through each file
#     for file_name in file_list:
#         print(file_name)

example_test_files/revealed_targets.csv
example_test_files/sample_submission.csv
example_test_files/test.csv
optiver2023/__init__.py
optiver2023/competition.cpython-310-x86_64-linux-gnu.so
public_timeseries_testing_util.py
train.csv

In [4]:
# training_file = "Final Project/optiver-trading-at-the-close/train.csv"
# df = pd.read_csv("optiver-trading-at-the-close/train.csv")

In [6]:
# split_size = len(df) // 3

# # Create three separate DataFrames
# df_part_1 = df.iloc[:split_size]
# df_part_2 = df.iloc[split_size:2*split_size]
# df_part_3 = df.iloc[2*split_size:]

# # Save each part as a separate CSV
# df_part_1.to_csv("train_part_1.csv", index=False)
# df_part_2.to_csv("train_part_2.csv", index=False)
# df_part_3.to_csv("train_part_3.csv", index=False)

In [11]:
## How to read the training data now
file_path = "optiver_training_data/train_part_1.csv.zip"
df_1 = pd.read_csv(file_path, compression='zip')

file_path = "optiver_training_data/train_part_2.csv.zip"
df_2 = pd.read_csv(file_path, compression='zip')

file_path = "optiver_training_data/train_part_3.csv.zip"
df_3 = pd.read_csv(file_path, compression='zip')

In [12]:
df = pd.concat([df_1, df_2, df_3], ignore_index=True)
df.head()

,stock_id,date_id,seconds_in_bucket,imbalance_size,imbalance_buy_sell_flag,reference_price,matched_size,far_price,near_price,bid_price,bid_size,ask_price,ask_size,wap,target,time_id,row_id
0,0,0,0,3180602.69,1,0.999812,13380276.64,NaN,NaN,0.999812,60651.50,1.000026,8493.03,1.0,-3.029704,0,0_0_0
1,1,0,0,166603.91,-1,0.999896,1642214.25,NaN,NaN,0.999896,3233.04,1.000660,20605.09,1.0,-5.519986,0,0_0_1
2,2,0,0,302879.87,-1,0.999561,1819368.03,NaN,NaN,0.999403,37956.00,1.000298,18995.00,1.0,-8.389950,0,0_0_2
3,3,0,0,11917682.27,-1,1.000171,18389745.62,NaN,NaN,0.999999,2324.90,1.000214,479032.40,1.0,-4.010200,0,0_0_3
4,4,0,0,447549.96,-1,0.999532,17860614.95,NaN,NaN,0.999394,16485.54,1.000016,434.10,1.0,-7.349849,0,0_0_4